using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xceed.Words.NET;
using System.Diagnostics;

namespace lab_11_microsoft_word
{
    class Program
    {
        static void Main(string[] args)
        {
            // create a new word document
            var document = DocX.Create("MyReport.docx");
            document.InsertParagraph("This is an amazing report");
            document.InsertParagraph($"Report generated by <<author>> at {DateTime.Now}");
            document.Save();

            Process.Start("WINWORD.EXE", "MyReport.docx");

            //TODO: Timer with a report
            //
            //Create folder
            //button go in WPF
                //Within folder create 1000 txt files
                //With one line of text
                //On a rerun of function
                    //on init, delete folder and files within
                //have stopwatch display time taken to create all the txt files
                //generate microsoft word file with saying time taken and what was done.

            //experiment with different amount of lines
            //report the times for each of these runs as well.

            //take name of permissions 2hrs work

            //lab 09

        }
    }
}
