//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_32_2_table_homework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int CatId { get; set; }
        public string CatName { get; set; }
        public Nullable<int> CatAge { get; set; }
        public Nullable<int> BreedId { get; set; }
    
        public virtual Breed Breed { get; set; }
    }
}
